### ISSUE TITLE
Password reset prompt comes after MFA registration

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-security-extensions#4]
### Description
If an admin sets a user account to require a password reset on next login, and MFA is enabled on a site, a user will be prompted to register with MFA before they are prompted for a new password.

I think it makes sense to prompt for the new password before MFA registration.
- It's less relevant if the user has since been asked to do another task
- The end of the MFA flow says something like 'Complete. Continue to the CMS', but then gets the unexpected password reset form.
- Until the password reset, it shouldn't be seen as a valid user who's permitted to register with MFA

### Expected behaviour
If a member has been flagged for a password reset on login, and MFA is enable for a site, they should receive the password reset prompt before MFA registration, but not authentication - that should still happen afterwards.

**Comment by NightJar** [comment]
To be clear: this is expected behaviour for verification - a user should only be able to change a member's password after they have successfully authenticated as that member.

This issue is specifically addressing the MFA registration flow, on a site that has enabled or required MFA since the user last logged in (before their password expired).

In this (somewhat edge) case, a user would be required to set up a `MFARegisteredMethod` before being required to choose a new password. This is not a bad thing (to my knowledge), it just "feels" backwards.

**Comment by robbieaverill** [comment]
I don't think this is worth the effort to change to be honest - reason being, we're going to introduce complexity to the way we handle the flow, which comes with added maintenance burden and risk, for minimal gain (IMO)

**Comment by NightJar** [comment]
Yeh, I'm agreement to close.
@brynwhyman thoughts?

**Comment by brynwhyman** [comment]
Fine by me. Closing.
